### ISSUE TITLE
hide the location bar for the twitter app tab

### ISSUE THREAD

**Issue by erikvold** [mozilla/twitter-address-bar-search#1]
or at least make this an option.

**Comment by erikvold** [comment]
maybe for a follow-up: clicking ctrl+l would reveal the location bar again until the page gets the focus.

**Comment by Mardak** [comment]
Could use the inContentWhitelist or rely on other functionality hiding toolbars on app tabs like mozilla/prospector#478

**Comment by erikvold** [comment]
WIP: https://github.com/mozilla/twitter-address-bar-search/compare/erikvold:issue-1

**Comment by erikvold** [comment]
Hey @Mardak, I think my [issue-1](https://github.com/mozilla/twitter-address-bar-search/compare/erikvold:issue-1) branch is ready for a review when you have a chance.

**Comment by erikvold** [comment]
oh right the `TAB_ATTR_NAME = "data-twitter";` part needs to be updated, any suggestions?
