### ISSUE TITLE
Addon not compatible with the latest version of Firefox Stable, Aurora and Nightly

### ISSUE THREAD

**Issue by pstoev** [mozilla/twitter-address-bar-search#12]
Really handy add-on that's been left unattended.
## Description

This add-on is not compatible with neither of the latest versions of:
- Firefox Stable (being version 34.0)
- Firefox Aurora (version 35)
- Firefox Nightly (version 36)

**Comment by baptx** [comment]
I don't know why this addon is no longer updated but there was a terrible bug which didn't allowed you to enter any website URL in address bar: https://twitter.com/baptx/statuses/515110972663808000 https://addons.mozilla.org/en-US/firefox/addon/twitter-address-bar-search/reviews/599284/

**Comment by AJCrowley** [comment]
I wish they'd update this plugin for Quantum.
