### ISSUE TITLE
option to have twitter searches made in twitter app tab

### ISSUE THREAD

**Issue by erikvold** [mozilla/twitter-address-bar-search#2]
To Reproduce:

In a non twitter app tab, do a search for `@name` in the location bar, and use the 'search for @name` twitter result.

Expected:
Focus switches to twitter app tab, and the location there is changed

Actual:
The location of the current tab is changed.

I think that the current behavior should be default, but I'd like the option to change this.

**Comment by Mardak** [comment]
I would assume that this is only if you still have the twitter app tab open? What if the app tab is closed?

**Comment by erikvold** [comment]
> I would assume that this is only if you still have the twitter app tab open?

yah

> What if the app tab is closed?

using the current tab seems fine, although another option is to re-open the app tab, maybe this should be another user pref?
